export const martialAchievements = [
  {
    id: "first_budo",
    name: "初太刀",
    rarity: "一般",
    comment: "ようやく武の道へ足を踏み入れた。",
  },
  {
    id: "ten_xp",
    name: "木刀持ち",
    rarity: "一般",
    comment: "木刀を持つ姿だけは一人前。",
  },
  {
    id: "fifty_xp",
    name: "道場の常連",
    rarity: "希少",
    comment: "家より道場にいる時間が長い。",
  },
  {
    id: "hundred_xp",
    name: "百本斬り",
    rarity: "希少",
    comment: "肩と前腕が反乱を始めた。",
  },
  {
    id: "threehundred_xp",
    name: "兵法者",
    rarity: "英傑",
    comment: "少しだけ武芸者らしくなった。",
  },
  {
    id: "thousand_xp",
    name: "現代サムライ",
    rarity: "伝説",
    comment: "もはや趣味とは呼べない。",
  },
  {
    id: "xp_2000",
    name: "道場の柱",
    rarity: "伝説",
    comment: "柱というより居座っている。",
  },
  {
    id: "xp_3000",
    name: "武芸百般",
    rarity: "神話",
    comment: "履歴書に書くには濃すぎる。",
  },
  {
    id: "xp_5000",
    name: "剣聖予備軍",
    rarity: "神話",
    comment: "普通の生活とは距離を置いた。",
  },
  {
    id: "ultimate_bushi",
    name: "武神",
    rarity: "神話",
    comment: "道場に住民票がありそう。",
  },

  {
    id: "iai_first",
    name: "初抜刀",
    rarity: "一般",
    comment: "抜いた。問題はそこからである。",
  },
  {
    id: "iai_50",
    name: "抜刀五十本",
    rarity: "一般",
    comment: "少し刀に顔を覚えられた。",
  },
  {
    id: "iai_100",
    name: "抜刀百本",
    rarity: "希少",
    comment: "鞘もそろそろ疲れている。",
  },
  {
    id: "iai_300",
    name: "抜刀術士",
    rarity: "英傑",
    comment: "刀を抜く速度だけは速い。",
  },
  {
    id: "iai_500",
    name: "居合家",
    rarity: "英傑",
    comment: "静かに見えてだいぶ変人。",
  },
  {
    id: "iai_1000",
    name: "居合の住人",
    rarity: "伝説",
    comment: "抜く前から顔が真剣。",
  },
  {
    id: "iai_2000",
    name: "鞘鳴りの達人",
    rarity: "伝説",
    comment: "鞘の音に人生を賭け始めた。",
  },
  {
    id: "iai_3000",
    name: "無拍子",
    rarity: "神話",
    comment: "速いのか遅いのか説明不能。",
  },
  {
    id: "iai_5000",
    name: "居合剣聖",
    rarity: "神話",
    comment: "もう刀が本体かもしれない。",
  },
  {
    id: "iai_hidden_1",
    name: "抜かぬ剣豪",
    rarity: "隠し",
    comment: "抜かずに済むならそれが一番。",
  },

  {
    id: "kenjutsu_first",
    name: "初剣術",
    rarity: "一般",
    comment: "とりあえず振った。まだ棒である。",
  },
  {
    id: "kenjutsu_50",
    name: "素振り五十本",
    rarity: "一般",
    comment: "肩が少し文句を言い始めた。",
  },
  {
    id: "kenjutsu_100",
    name: "素振り百本",
    rarity: "希少",
    comment: "竹刀に生活感が出てきた。",
  },
  {
    id: "kenjutsu_300",
    name: "剣豪見習い",
    rarity: "英傑",
    comment: "まだ剣豪ではない。",
  },
  {
    id: "kenjutsu_500",
    name: "剣士",
    rarity: "英傑",
    comment: "話し合いより間合いを見がち。",
  },
  {
  id: "kenjutsu_1000",
  name: "剣豪",
  rarity: "伝説",
  comment: "だいぶ話が通じなくなってきた。",
},
{
  id: "kenjutsu_2000",
  name: "兵法家",
  rarity: "伝説",
  comment: "何でも兵法に例え始める。",
},
{
  id: "kenjutsu_3000",
  name: "柳生気取り",
  rarity: "隠し",
  comment: "まだ気取りである。",
},
{
  id: "kenjutsu_5000",
  name: "剣聖",
  rarity: "神話",
  comment: "周囲が勝手に神格化する。",
},

{
  id: "jujutsu_first",
  name: "初受身",
  rarity: "一般",
  comment: "床との対話が始まった。",
},
{
  id: "jujutsu_50",
  name: "受身職人",
  rarity: "一般",
  comment: "転ぶのが少し上手くなった。",
},
{
  id: "jujutsu_100",
  name: "投げられ慣れ",
  rarity: "希少",
  comment: "感覚がおかしくなってきた。",
},
{
  id: "jujutsu_300",
  name: "柔の達人",
  rarity: "英傑",
  comment: "投げられる側も卒業したい。",
},
{
  id: "jujutsu_500",
  name: "古流柔術家",
  rarity: "英傑",
  comment: "説明が長くなり始める。",
},
{
  id: "jujutsu_1000",
  name: "捕手",
  rarity: "伝説",
  comment: "いつの間にか掴んでいる。",
},
{
  id: "jujutsu_2000",
  name: "崩しの鬼",
  rarity: "伝説",
  comment: "立っていることを許さない。",
},
{
  id: "jujutsu_3000",
  name: "柔術仙人",
  rarity: "神話",
  comment: "もはや力学そのもの。",
},

{
  id: "dojo_10",
  name: "道場の住人",
  rarity: "一般",
  comment: "帰宅頻度が減り始めた。",
},
{
  id: "dojo_30",
  name: "道場の主",
  rarity: "希少",
  comment: "鍵を持ってそう。",
},
{
  id: "dojo_50",
  name: "畳の妖精",
  rarity: "英傑",
  comment: "だいたいいつもいる。",
},
{
  id: "dojo_100",
  name: "畳神",
  rarity: "神話",
  comment: "畳に人格が宿った。",
},

{
  id: "hidden_1",
  name: "竹刀破壊者",
  rarity: "隠し",
  comment: "また買うのか。",
},
{
  id: "hidden_2",
  name: "木刀収集家",
  rarity: "隠し",
  comment: "何本あれば満足なのか。",
},
{
  id: "hidden_3",
  name: "帯コレクター",
  rarity: "隠し",
  comment: "段位より本数が多い。",
},
{
  id: "hidden_4",
  name: "稽古後のビール",
  rarity: "隠し",
  comment: "真の目的はこちら。",
},
{
  id: "hidden_5",
  name: "正座耐久王",
  rarity: "隠し",
  comment: "足の感覚は置いてきた。",
},
{
  id: "hidden_6",
  name: "現代の浪人",
  rarity: "隠し",
  comment: "所属より自由を選んだ。",
},
{
  id: "hidden_7",
  name: "武芸オタク",
  rarity: "隠し",
  comment: "一般人との温度差が大きい。",
},
{
  id: "hidden_8",
  name: "館長候補",
  rarity: "隠し",
  comment: "責任だけ増える。",
},
{
  id: "hidden_9",
  name: "道場に住民票",
  rarity: "神話",
  comment: "そろそろ本当に怪しい。",
},
{
  id: "hidden_10",
  name: "古流の住人",
  rarity: "神話",
  comment: "もはや現代がサブ。",
},
{
  id: "toyosu_1",
  name: "豊洲の見習い",
  rarity: "一般",
  comment: "海老より先に起きる生活。",
},
{
  id: "toyosu_2",
  name: "豊洲の住人",
  rarity: "希少",
  comment: "市場の匂いで季節が分かる。",
},
{
  id: "shrimp_master",
  name: "海老の目利き",
  rarity: "英傑",
  comment: "冷凍庫の前で本気になる。",
},
{
  id: "shrimp_god",
  name: "海老神",
  rarity: "神話",
  comment: "もはや甲殻類側の存在。",
},

{
  id: "beef_tongue_1",
  name: "牛タン商人",
  rarity: "一般",
  comment: "気付けばタンの話ばかり。",
},
{
  id: "beef_tongue_2",
  name: "豪州タンの伝道師",
  rarity: "英傑",
  comment: "焼肉屋より詳しい。",
},
{
  id: "beef_tongue_3",
  name: "タン仙人",
  rarity: "神話",
  comment: "牛も少し困惑している。",
},

{
  id: "samurai_move_1",
  name: "サムライムーブメント",
  rarity: "一般",
  comment: "最初の一歩を踏み出した。",
},
{
  id: "samurai_move_2",
  name: "現代武芸伝道師",
  rarity: "英傑",
  comment: "説明が止まらなくなる。",
},
{
  id: "samurai_move_3",
  name: "サムライインフルエンサー",
  rarity: "伝説",
  comment: "再生数より熱量が高い。",
},

{
  id: "app_1",
  name: "武芸手帳開発者",
  rarity: "一般",
  comment: "まず白画面と戦う。",
},
{
  id: "app_2",
  name: "バグ斬り",
  rarity: "希少",
  comment: "コードにも抜刀術。",
},
{
  id: "app_3",
  name: "React剣士",
  rarity: "英傑",
  comment: "useStateを振り回す。",
},
{
  id: "app_4",
  name: "白画面討伐者",
  rarity: "伝説",
  comment: "何度倒れても立ち上がる。",
},
{
  id: "app_5",
  name: "武芸手帳館主",
  rarity: "神話",
  comment: "最初の館長。",
},

{
  id: "diet_1",
  name: "沼の住人",
  rarity: "一般",
  comment: "今日も沼を食べている。",
},
{
  id: "diet_2",
  name: "スーパー大麦使い",
  rarity: "希少",
  comment: "腸内環境に詳しくなる。",
},
{
  id: "diet_3",
  name: "減量武者",
  rarity: "英傑",
  comment: "脂肪との戦が始まる。",
},
{
  id: "diet_4",
  name: "体脂肪率15%",
  rarity: "伝説",
  comment: "ここからが本番。",
},

{
  id: "walk_1",
  name: "一万歩の旅人",
  rarity: "一般",
  comment: "地味だが強い。",
},
{
  id: "walk_2",
  name: "二万歩武者",
  rarity: "希少",
  comment: "脚が抗議している。",
},
{
  id: "walk_3",
  name: "江戸徒歩参勤",
  rarity: "英傑",
  comment: "電車を忘れた男。",
},

{
  id: "budo_nerd",
  name: "古武術オタク",
  rarity: "隠し",
  comment: "一般人との温度差が大きい。",
},
{
  id: "history_nerd",
  name: "兵法談義",
  rarity: "隠し",
  comment: "雑談が戦国時代になる。",
},
{
  id: "ultimate_shohei",
  name: "下越翔平",
  rarity: "神話",
  comment: "本人限定解除実績。",
},
{
  id: "vr_1",
  name: "VR武者",
  rarity: "一般",
  comment: "現実だけでは足りなくなった。",
},
{
  id: "vr_2",
  name: "仮想道場主",
  rarity: "希少",
  comment: "畳もサーバーに置く時代。",
},
{
  id: "vr_3",
  name: "VR剣豪",
  rarity: "英傑",
  comment: "斬った相手はポリゴン。",
},
{
  id: "vr_4",
  name: "未来の兵法者",
  rarity: "伝説",
  comment: "古流とVRを混ぜるな危険。",
},

{
  id: "ai_1",
  name: "AI秘書の主",
  rarity: "一般",
  comment: "自分で自分を管理し始めた。",
},
{
  id: "ai_2",
  name: "AI館主",
  rarity: "希少",
  comment: "ついに館主まで自動化。",
},
{
  id: "ai_3",
  name: "機械仕掛けの軍師",
  rarity: "英傑",
  comment: "人間より先に予定を把握する。",
},
{
  id: "ai_4",
  name: "令和の参謀",
  rarity: "伝説",
  comment: "軍議がだいたいチャット。",
},

{
  id: "invest_1",
  name: "投資武者",
  rarity: "一般",
  comment: "相場にも間合いがある。",
},
{
  id: "invest_2",
  name: "チャート剣士",
  rarity: "希少",
  comment: "ローソク足を見すぎている。",
},
{
  id: "invest_3",
  name: "含み損兵法",
  rarity: "隠し",
  comment: "耐えることもまた修行。",
},
{
  id: "invest_4",
  name: "利確侍",
  rarity: "英傑",
  comment: "欲を斬るのが一番難しい。",
},

{
  id: "trading_1",
  name: "輸入商社の侍",
  rarity: "一般",
  comment: "見積と稽古を両方こなす。",
},
{
  id: "trading_2",
  name: "CFRの兵法者",
  rarity: "希少",
  comment: "価格条件まで武芸に見える。",
},
{
  id: "trading_3",
  name: "冷凍庫の軍師",
  rarity: "英傑",
  comment: "在庫と戦略を同時に見る。",
},
{
  id: "trading_4",
  name: "商談剣豪",
  rarity: "伝説",
  comment: "値決めにも残心が必要。",
},

{
  id: "humor_1",
  name: "皮肉の達人",
  rarity: "一般",
  comment: "口だけは初段以上。",
},
{
  id: "humor_2",
  name: "館主の毒舌",
  rarity: "希少",
  comment: "褒めているのか怪しい。",
},
{
  id: "humor_3",
  name: "腐しの名人",
  rarity: "英傑",
  comment: "説明文がだんだん辛い。",
},
{
  id: "humor_4",
  name: "笑う剣豪",
  rarity: "伝説",
  comment: "真剣なのにふざけている。",
},

{
  id: "legend_1",
  name: "令和の武芸者",
  rarity: "英傑",
  comment: "時代とのズレを武器にした。",
},
{
  id: "legend_2",
  name: "古流と未来",
  rarity: "伝説",
  comment: "組み合わせがだいぶ変。",
},
{
  id: "legend_3",
  name: "自分専用RPG",
  rarity: "伝説",
  comment: "人生をゲーム化し始めた。",
},
{
  id: "legend_4",
  name: "武芸アプリ創始者",
  rarity: "神話",
  comment: "誰も頼んでないのに作った。",
},
{
  id: "legend_5",
  name: "現代サムライ完成体",
  rarity: "神話",
  comment: "もうジャンルが分からない。",
},
];