export const titles = [
  {
    id: "modern_samurai",
    name: "現代サムライ",
    description: "武芸と現代を両立する者",
    condition: "初期称号",
  },
  {
    id: "tatami_fairy",
    name: "畳の妖精",
    description: "気付くと道場にいる",
    condition: "累計XP100達成",
  },
  {
    id: "shrimp_god",
    name: "海老神",
    description: "甲殻類と心を通わせた者",
    condition: "隠し条件",
  },
  {
    id: "dojo_master",
    name: "道場の主",
    description: "館主より先に来る",
    condition: "累計XP1000達成",
  },
  {
    id: "sword_saint",
    name: "剣聖",
    description: "説明不能な領域",
    condition: "総合段位が極限に近づく",
  },
  {
    id: "bug_slayer",
    name: "白画面討伐者",
    description: "Reactの魔物を斬った",
    condition: "実績5個解除",
  },
  {
    id: "budo_nerd",
    name: "古武術オタク",
    description: "一般人との温度差あり",
    condition: "総合スコア70以上",
  },
  {
    id: "ultimate_shohei",
    name: "下越翔平",
    description: "本人限定称号",
    condition: "隠し条件",
  },

  { id: "first_budo", name: "初太刀", description: "最初の一歩", condition: "武芸記録を1回保存" },
  { id: "wooden_sword", name: "木刀持ち", description: "稽古を始めた者", condition: "武芸XP25達成" },
  { id: "dojo_regular", name: "道場の常連", description: "通う者は強い", condition: "武芸XP100達成" },
  { id: "hundred_cut", name: "百本斬り", description: "数を積んだ者", condition: "武芸XP300達成" },
  { id: "heihosha", name: "兵法者", description: "技だけでなく理も見る者", condition: "武芸XP1000達成" },
  { id: "modern_bushi", name: "現代武士", description: "仕事も稽古も斬る", condition: "累計XP3000達成" },
  { id: "dojo_pillar", name: "道場の柱", description: "場を支える者", condition: "実績20個解除" },

  { id: "iai_beginner", name: "初抜刀", description: "鞘から物語が始まる", condition: "居合XP25達成" },
  { id: "iai_50", name: "抜刀五十本", description: "抜くほどに整う", condition: "居合XP50達成" },
  { id: "iai_100", name: "抜刀百本", description: "抜刀が習慣になった者", condition: "居合XP100達成" },
  { id: "iai_master", name: "居合家", description: "静の中に刃を持つ", condition: "居合XP300達成" },
  { id: "iai_resident", name: "居合の住人", description: "日常が鞘の中にある", condition: "居合XP700達成" },
  { id: "iai_saint", name: "居合剣聖", description: "抜く前に勝つ者", condition: "居合XP1500達成" },

  { id: "kenjutsu_beginner", name: "初剣術", description: "剣の道に入った者", condition: "剣術XP25達成" },
  { id: "suburi_50", name: "素振り五十本", description: "振れば分かる", condition: "剣術XP50達成" },
  { id: "suburi_100", name: "素振り百本", description: "百本は入口", condition: "剣術XP100達成" },
  { id: "kenshi", name: "剣士", description: "刃筋を見る者", condition: "剣術XP300達成" },
  { id: "kengo", name: "剣豪", description: "間合いを支配する者", condition: "剣術XP700達成" },
  { id: "heihoka", name: "兵法家", description: "勝ち筋を読む者", condition: "剣術XP1500達成" },

  { id: "jujutsu_beginner", name: "初受身", description: "倒れて学ぶ者", condition: "柔術XP25達成" },
  { id: "ukemi_master", name: "受身職人", description: "転んでもただでは起きない", condition: "柔術XP50達成" },
  { id: "nage_rare", name: "投げられ慣れ", description: "畳と仲が良い", condition: "柔術XP100達成" },
  { id: "koryu_jujutsu", name: "古流柔術家", description: "崩しを知る者", condition: "柔術XP300達成" },
  { id: "kuzushi_oni", name: "崩しの鬼", description: "相手の軸を奪う者", condition: "柔術XP700達成" },
  { id: "jujutsu_sennin", name: "柔術仙人", description: "力まず制する者", condition: "柔術XP1500達成" },

  { id: "toyosu_1", name: "豊洲の見習い", description: "市場の空気を知る者", condition: "隠し条件" },
  { id: "toyosu_2", name: "豊洲の住人", description: "市場に馴染みすぎた者", condition: "隠し条件" },
  { id: "shrimp_master", name: "海老の目利き", description: "海老を見る目が違う", condition: "隠し条件" },
  { id: "beef_tongue_1", name: "牛タン商人", description: "タンの価値を知る者", condition: "隠し条件" },
  { id: "beef_tongue_2", name: "豪州タンの伝道師", description: "豪州タンを広める者", condition: "隠し条件" },

  { id: "app_1", name: "武芸手帳開発者", description: "武芸をアプリに刻む者", condition: "アプリ開発開始" },
  { id: "app_2", name: "バグ斬り", description: "エラーを恐れない者", condition: "開発系実績解除" },
  { id: "app_3", name: "React剣士", description: "コンポーネントを斬り分ける者", condition: "Hook分離達成" },
  { id: "app_4", name: "白画面討伐者", description: "白画面から帰還した者", condition: "実績5個解除" },
  { id: "app_5", name: "武芸手帳館主", description: "この館を作った者", condition: "称号図鑑作成" },

  { id: "diet_1", name: "沼の住人", description: "沼と共に減量する者", condition: "身体記録を継続" },
  { id: "diet_2", name: "スーパー大麦使い", description: "食物繊維の使い手", condition: "隠し条件" },
  { id: "diet_3", name: "減量武者", description: "脂肪を斬る者", condition: "体重記録を継続" },
  { id: "walk_1", name: "一万歩の旅人", description: "歩いて進む者", condition: "歩数記録連動予定" },
  { id: "walk_2", name: "二万歩武者", description: "歩きすぎの武者", condition: "歩数記録連動予定" },

  { id: "legend_1", name: "令和の武芸者", description: "現代に武芸を残す者", condition: "総合条件達成" },
  { id: "legend_2", name: "古流と未来", description: "古流を未来へ運ぶ者", condition: "最終到達称号" },
  { id: "walk_5000", name: "散歩侍" },
  { id: "walk_10000", name: "一万歩の旅人" },
  { id: "walk_20000", name: "二万歩武者" },
  { id: "walk_30000", name: "徒歩仙人" },
  { id: "first_technique", name: "初伝" },
  { id: "technique_10", name: "武芸者" },
  { id: "technique_20", name: "技の蒐集家" },
  { id: "teacher_5", name: "小さき指南役" },
  { id: "teacher_10", name: "武芸指南役" },

];